name = "Efeito Rede"
license = "GPL-3.0"
licenselink = "https://github.com/htko89/hugo-theme-foundation6-blog/blob/master/license.txt"
description = "Growth Hacking, Mrketing Digtal e atalhos para o crescimento de startups"
homepage = "http://efeitorede.com"
tags = ["growth hack", "marketing", "digital"]
features = ["responsive", "blog"]
min_version = 0.17

[author]
  name = "Bruno Etchepare"
  homepage = "http://www.growthstreak.com"


# [original]
#   author = "zurb"
#   homepage = "http://foundation.zurb.com/templates-previews-sites-f6/blog.html"
#   repo = "https://github.com/zurb/foundation-zurb-template"
